//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceProxy.TestService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TestService.ITestService")]
    public interface ITestService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/TestCall", ReplyAction="http://tempuri.org/ITestService/TestCallResponse")]
        string TestCall(int value, bool simulateExceptions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/TestCall", ReplyAction="http://tempuri.org/ITestService/TestCallResponse")]
        System.Threading.Tasks.Task<string> TestCallAsync(int value, bool simulateExceptions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/ResetCache", ReplyAction="http://tempuri.org/ITestService/ResetCacheResponse")]
        void ResetCache();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestService/ResetCache", ReplyAction="http://tempuri.org/ITestService/ResetCacheResponse")]
        System.Threading.Tasks.Task ResetCacheAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestServiceChannel : WcfServiceProxy.TestService.ITestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestServiceClient : System.ServiceModel.ClientBase<WcfServiceProxy.TestService.ITestService>, WcfServiceProxy.TestService.ITestService {
        
        public TestServiceClient() {
        }
        
        public TestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string TestCall(int value, bool simulateExceptions) {
            return base.Channel.TestCall(value, simulateExceptions);
        }
        
        public System.Threading.Tasks.Task<string> TestCallAsync(int value, bool simulateExceptions) {
            return base.Channel.TestCallAsync(value, simulateExceptions);
        }
        
        public void ResetCache() {
            base.Channel.ResetCache();
        }
        
        public System.Threading.Tasks.Task ResetCacheAsync() {
            return base.Channel.ResetCacheAsync();
        }
    }
}
